---
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-deploy-pages.yml@aa293579a6680b0264333447ddad4752244ebdb0 # v0.4.0
    with:
      build-command: 'bun run build'
      source-path: 'dist'
    permissions:
      contents: read
      pages: write
      id-token: write
